#!/usr/bin/env python3
"""Download the woff2 faces the site uses into public/fonts/ and print the
matching @font-face rules for public/css/style.css.

The site self-hosts its fonts so the page makes no third-party requests.
Run from the repo root when a face needs to be added or refreshed:

    python3 scripts/fetch-fonts.py

Google serves one variable file per (family, style, subset), so several
weights can resolve to identical bytes; identical files are stored once and
the rule for them spans the whole weight range.
"""

import hashlib
import os
import re
import urllib.request

FAMILIES = "family=Arimo:ital,wght@0,400;0,700;1,400;1,700&family=Cutive+Mono"
SUBSETS = ("latin", "latin-ext")
FONT_DIR = os.path.join("public", "fonts")
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")


def fetch(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})).read()


def faces():
    """(family, style, weight, subset, unicode-range, url) for each face."""
    css = fetch("https://fonts.googleapis.com/css2?%s&display=swap" % FAMILIES).decode()
    for subset, body in re.findall(r"/\* ([\w-]+) \*/\s*@font-face \{(.*?)\}", css, re.S):
        if subset not in SUBSETS:
            continue
        yield (re.search(r"font-family: '([^']+)'", body).group(1),
               re.search(r"font-style: (\w+)", body).group(1),
               int(re.search(r"font-weight: (\d+)", body).group(1)),
               subset,
               re.search(r"unicode-range: ([^;]+);", body).group(1),
               re.search(r"url\((https://[^)]+)\)", body).group(1))


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    by_content = {}   # sha1 -> file name
    rules = {}        # (family, style, subset, file name) -> [weights, unicode-range]

    for family, style, weight, subset, urange, url in faces():
        data = fetch(url)
        digest = hashlib.sha1(data).hexdigest()
        if digest not in by_content:
            name = "%s-%s-%s.woff2" % (
                family.lower().replace(" ", "-"), style, subset)
            if name in by_content.values():           # same face, differing bytes
                name = name.replace(".woff2", "-%d.woff2" % weight)
            with open(os.path.join(FONT_DIR, name), "wb") as f:
                f.write(data)
            by_content[digest] = name
        key = (family, style, subset, by_content[digest])
        rules.setdefault(key, [set(), urange])[0].add(weight)

    print("/* Self-hosted so the page makes no third-party requests.")
    print("   Generated by scripts/fetch-fonts.py -- see that file to refresh. */")
    for (family, style, _subset, name), (weights, urange) in rules.items():
        span = (str(min(weights)) if len(weights) == 1
                else "%d %d" % (min(weights), max(weights)))
        print("\n@font-face {")
        print("  font-family: '%s';" % family)
        print("  font-style: %s;" % style)
        print("  font-weight: %s;" % span)
        print("  font-display: swap;")
        print("  src: url(../fonts/%s) format('woff2');" % name)
        print("  unicode-range: %s;" % urange)
        print("}")


if __name__ == "__main__":
    main()
