#!/usr/bin/env sh
# Confirms the live site is serving THIS repo's build, not the 2016 one.
#
# Run after the Pages source is switched to "GitHub Actions" and the deploy
# workflow has completed. Rebuilds locally and compares bytes, so a pass means
# the deployed bundle is identical to what this working tree produces -- not
# just that the URL returned something with a hash in its name.
#
#   sh scripts/verify-deploy.sh
#
# Exits 0 only if every check passes.

set -eu

URL="${1:-https://richardharrington.github.io/income-converter/}"
NOCACHE="-H Cache-Control:no-cache -H Pragma:no-cache"
fail=0
say() { printf '%-34s %s\n' "$1" "$2"; }
bad() { say "$1" "FAIL  $2"; fail=1; }
ok()  { say "$1" "ok    $2"; }

# Build locally from the current tree, into a scratch dir we can hash.
echo "Building locally for comparison..."
npx shadow-cljs release app >/dev/null
local_js=$(ls public/js/main.*.js 2>/dev/null | head -1)
[ -n "$local_js" ] || { echo "no local release bundle -- build failed?"; exit 1; }
local_name=$(basename "$local_js")
local_sum=$(shasum -a 256 "$local_js" | cut -d' ' -f1)
echo "Local bundle: $local_name"
echo

index=$(curl -fsS $NOCACHE "$URL")

# 1. The page must reference the bundle this tree just built, by exact name.
served_name=$(printf '%s' "$index" | sed -n 's|.*<script[^>]*src="js/\([^"]*\)".*|\1|p')
if [ "$served_name" = "$local_name" ]; then
  ok "bundle name" "$served_name"
else
  bad "bundle name" "serving '${served_name:-none}', built '$local_name'"
fi

# 2. The 2016 build's script path must be gone.
if printf '%s' "$index" | grep -q 'js/compiled/income_converter.js'; then
  bad "2016 bundle path" "still referenced"
else
  ok "2016 bundle path" "gone"
fi

# 3. The page must be the generated one, not a hand-written file.
if printf '%s' "$index" | grep -q 'GENERATED by src/build_hooks.clj'; then
  ok "generated by build hook" "banner present"
else
  bad "generated by build hook" "banner missing"
fi

# 4. Fonts must be self-hosted -- no third-party request left in the page.
if printf '%s' "$index" | grep -q 'fonts.googleapis.com'; then
  bad "self-hosted fonts" "still linking Google Fonts"
else
  ok "self-hosted fonts" "no Google Fonts link"
fi

# 5. The decisive one: the served bytes must equal the bytes just built.
if [ -n "$served_name" ]; then
  served_sum=$(curl -fsS $NOCACHE "${URL%/}/js/$served_name" | shasum -a 256 | cut -d' ' -f1)
  if [ "$served_sum" = "$local_sum" ]; then
    ok "bundle bytes" "sha256 matches local build"
  else
    bad "bundle bytes" "sha256 differs (served $served_sum)"
  fi
fi

# 6. The self-hosted font must resolve. (style.css is NOT a useful identity
#    check -- the 2016 site serves a file at that same path.)
for asset in fonts/arimo-normal-latin.woff2 css/style.css; do
  code=$(curl -sS -o /dev/null -w '%{http_code}' "${URL%/}/$asset" 2>/dev/null || echo 000)
  [ "$code" = "200" ] && ok "$asset" "200" || bad "$asset" "HTTP $code"
done

echo
[ "$fail" -eq 0 ] && echo "Live site is this build." || echo "Live site is NOT this build."
exit "$fail"
