(ns build-hooks
  "shadow-cljs build hook that generates public/index.html.

   public/index.template.html is the source of truth. The hook substitutes
   {{main-js}} with the file name shadow-cljs actually emitted -- main.js in
   dev, main.<hash>.js in a release build -- and swaps the template's
   <!--#template ...--> note for a short generated-file banner. Running as a
   build hook rather than a separate script keeps dev and release on one
   code path."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.string :as str]))

(def ^:private template-file (io/file "public" "index.template.html"))
(def ^:private index-file (io/file "public" "index.html"))

(defn- main-output-name
  "The emitted file name of the :main module, per the build manifest."
  [manifest-file]
  (when-not (.exists manifest-file)
    (throw (ex-info "build hook: build manifest not found"
                    {:file (.getAbsolutePath manifest-file)})))
  (let [manifest (edn/read-string (slurp manifest-file))]
    (or (some #(when (= :main (:module-id %)) (:output-name %)) manifest)
        (throw (ex-info "build hook: no :main module in build manifest"
                        {:manifest manifest})))))

(def ^:private banner
  "<!-- GENERATED by src/build_hooks.clj from index.template.html. Do not edit. -->\n")

(def ^:private template-comment
  #"(?s)<!--#template.*?-->\n?")

(defn write-index
  {:shadow.build/stage :flush}
  [build-state & _]
  (let [{:keys [output-dir manifest-name]} (:build-options build-state)
        output-name (main-output-name
                     (io/file output-dir (or manifest-name "manifest.edn")))]
    (->> (-> (slurp template-file)
             (str/replace template-comment (constantly banner))
             (str/replace "{{main-js}}" output-name))
         (spit index-file))
    (println (str "build hook: wrote " (.getPath index-file)
                  " referencing js/" output-name)))
  build-state)
